---
- name: Install k8s cluster
  hosts: all
  become: yes
  become_user: root
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
  - prep_os
  - install_kubernetes_vbox
  - install_calico_cni