---
# tasks file for k8s-vbox

- include_tasks: update_os.yml
- include_tasks: set_hosts_file.yml
- include_tasks: disable_swap.yml
- include_tasks: prep_env_containerd.yml
- include_tasks: add_modules.yml
- include_tasks: set_sysctl.yml
- include_tasks: add_gpgkeys_repoes.yml
- include_tasks: install_packages.yml
- include_tasks: configure_containerd.yml
- include_tasks: initialize_kubernetes.yml

