---
# Prepare env for containerd

- name: Check containerd.conf is exists
  ansible.builtin.stat:
    path: "{{ modules_path }}/containerd.conf"
  register: containerd_conf

- name: Create containerd.conf and set its permission
  ansible.builtin.file:
    path: "{{ modules_path }}/containerd.conf"
    state: touch
    mode: 0644
  when: containerd_conf.stat.exists == False

- name: Set containerd.conf
  ansible.builtin.blockinfile:
    path: "{{ modules_path }}/containerd.conf"
    block: |
      overlay
      br_netfilter
  when: containerd_conf.stat.exists == False