---
# Disable SWAP

- name: Disable SWAP
  ansible.builtin.command: swapoff -a
  when: "ansible_memory_mb.swap.total > 0"

- name: Disable SWAP in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(\s?\/swap+.+)$'
    replace: '# \1'
  when: "ansible_memory_mb.swap.total > 0"