---
# tasks file for install_kubernetes_vbox

- include_tasks: disable_swap.yml
- include_tasks: prep_env_containerd.yml
- include_tasks: add_modules.yml
- include_tasks: set_sysctl.yml
- include_tasks: install_packages.yml
- include_tasks: configure_containerd.yml
- include_tasks: initialize_kubernetes.yml

